ci: ver bump via checklist-release

diff --git a/.github/workflows/bnd.yml b/.github/workflows/bnd.yml
--- a/.github/workflows/bnd.yml
+++ b/.github/workflows/bnd.yml
@@ -42,15 +42,15 @@ jobs:
         with:
           NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
 
-      # - name: fork | build
-      #   # id: build
-      #   # continue-on-error: false
-      #   shell: bash
-      #   run: |
-      #     pnpm build:fast || {
-      #       echo "build failed with exit code $?"
-      #       exit 1
-      #     }
+      - name: fork | build
+        # id: build
+        # continue-on-error: false
+        shell: bash
+        run: |
+          pnpm build:fast || {
+            echo "build failed with exit code $?"
+            exit 1
+          }
       
       - name: action | changesets/NPM-release
         uses: vezham/v0xFE-deployer/.github/actions/changesets/release@timeline
