ci: poc main-poc

diff --git a/.github/workflows/main-poc.yml b/.github/workflows/main-poc.yml
--- a/.github/workflows/main-poc.yml
+++ b/.github/workflows/main-poc.yml
@@ -1,12 +1,16 @@
-# wjdlz/NOTE: ci@1.0.5-final-check
-name: POC
+# wjdlz/NOTE: ci@1.0.5
+name: bnd
 
 on:
   push:
-    branches: [feat/npm]
+    branches: [feat/npm, -timeline]
+    paths:
+      - ".github/workflows/bnd.yml"
+      - ".changeset/**"
+      - "packages/**"
 
 concurrency:
-  group: main-poc-${{ github.workflow }}-${{ github.ref }}
+  group: main-poc-bnd-${{ github.workflow }}-${{ github.ref }}
   cancel-in-progress: true
 # timeout-minutes: 10
 
@@ -17,11 +21,12 @@ permissions:
 
 env:
   REPO: ${{ github.repository || 'vezham/heroui' }} # inputs.GIT_REPO
-  BRANCH: ${{ github.ref_name || 'feat/npm' }} # inputs.GIT_BRANCH
+  BRANCH: ${{ github.ref_name || 'timeline' }} # inputs.GIT_BRANCH
 
 jobs:
-  npm-auth:
+  bnd:
     runs-on: ubuntu-latest
+    timeout-minutes: 30
     
     steps:
       - name: action | checkout | ${{ env.REPO }}@${{ env.BRANCH }}
@@ -34,6 +39,16 @@ jobs:
         uses: vezham/v0xFE-deployer/.github/actions/common/setup-install-npm@timeline
         with:
           NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
+      
+      - name: fork | Build
+        # id: build
+        continue-on-error: false
+        shell: bash
+        run: |
+          pnpm build:fast || {
+            echo "build failed with exit code $?"
+            exit 1
+          }
       
       - name: action | changesets/NPM-release
         uses: vezham/v0xFE-deployer/.github/actions/changesets/release@timeline
